# Generated by Django 2.0.1 on 2018-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('production_company', models.CharField(max_length=64)),
                ('rating_content', models.CharField(max_length=16)),
                ('rating_value', models.IntegerField()),
                ('url', models.CharField(max_length=256, unique=True)),
                ('opening_position', models.IntegerField()),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
